import type { DashboardState } from "./contracts";

export const previewState: DashboardState = {
  mode: "preview",
  refreshedAt: "2026-08-25T13:42:00Z",
  databasePath:
    "~/Library/Application Support/com.devie.quota/devie-quota.sqlite3",
  settings: { showMenuBarItem: true },
  connections: [
    {
      id: "claude-work",
      provider: "claude",
      kind: "oauth",
      label: "Claude · work@example.com",
      sourceLocator: "oauth/claude/u-1",
      enabled: true,
      status: "ready",
      source: "Claude subscription API",
      lastUpdatedAt: "2026-08-25T13:42:00Z",
      customLabel: "Work",
      identity: { displayName: "work@example.com", plan: "Max 5x" },
      windows: [
        {
          key: "five_hour",
          label: "Session (5h)",
          usedPercent: 63,
          resetsAt: "2026-08-25T15:00:00Z",
        },
        {
          key: "seven_day",
          label: "Weekly",
          usedPercent: 28,
          resetsAt: "2026-08-29T07:00:00Z",
        },
        {
          key: "seven_day_fable",
          label: "Fable (weekly)",
          usedPercent: 12,
          resetsAt: "2026-08-29T07:00:00Z",
        },
      ],
    },
    {
      id: "claude-personal",
      provider: "claude",
      kind: "local",
      label: "Claude CLI · Default",
      sourceLocator: "~/.claude",
      enabled: true,
      status: "stale",
      source: "Claude subscription API (cached)",
      lastUpdatedAt: "2026-08-25T13:28:00Z",
      identity: { displayName: "me@example.com", plan: "Pro" },
      windows: [
        {
          key: "five_hour",
          label: "Session (5h)",
          usedPercent: 18,
          resetsAt: "2026-08-25T16:00:00Z",
        },
        {
          key: "seven_day",
          label: "Weekly",
          usedPercent: 46,
          resetsAt: "2026-08-30T07:00:00Z",
        },
      ],
    },
    {
      id: "codex-default",
      provider: "codex",
      kind: "local",
      label: "Codex CLI · Default",
      sourceLocator: "~/.codex",
      enabled: true,
      status: "ready",
      source: "Codex local records",
      lastUpdatedAt: "2026-08-25T13:41:00Z",
      identity: { plan: "Plus" },
      windows: [
        {
          key: "primary",
          label: "Session (5h)",
          usedPercent: 41,
          resetsAt: "2026-08-25T15:34:00Z",
        },
        {
          key: "secondary",
          label: "Weekly",
          usedPercent: 71,
          resetsAt: "2026-08-28T09:00:00Z",
        },
      ],
    },
    {
      id: "copilot-mathdevie",
      provider: "copilot",
      kind: "local",
      label: "GitHub CLI · mathdevie",
      sourceLocator: "github.com/mathdevie",
      enabled: true,
      status: "ready",
      source: "GitHub CLI",
      lastUpdatedAt: "2026-08-25T13:40:00Z",
      identity: { displayName: "mathdevie", plan: "Copilot Pro" },
      windows: [
        {
          key: "premium_interactions",
          label: "Premium",
          usedPercent: 22,
          resetsAt: "2026-09-01T00:00:00Z",
        },
      ],
    },
  ],
};
