import type { CodexResetsStatus, DashboardState } from "./contracts";

export const previewState: DashboardState = {
  mode: "preview",
  refreshedAt: "2026-08-25T13:42:00Z",
  settings: {
    showMenuBarItem: true,
    traySummary: { connectionId: "claude-work", windowKey: "five_hour" },
    remoteAccess: {
      enabled: true,
      port: 47321,
      lan: false,
      token: "previewtokenpreviewtokenpreviewtoken1234",
      urls: ["http://localhost:47321"],
    },
  },
  connections: [
    {
      id: "claude-work",
      provider: "claude",
      label: "Claude · work@example.com",
      sourceLocator: "oauth/claude/u-1",
      enabled: true,
      status: "ready",
      source: "Claude subscription API",
      lastUpdatedAt: "2026-08-25T13:42:00Z",
      customLabel: "Work",
      identity: { displayName: "work@example.com", plan: "Max 5x" },
      alerts: { lowQuota: true, resetSoon: true, resetHappened: true },
      autoPing: {
        enabled: true,
        lastPingAt: "2026-08-25T10:00:03Z",
      },
      windows: [
        {
          key: "five_hour",
          label: "Session (5h)",
          usedPercent: 63,
          resetsAt: "2026-08-25T15:00:00Z",
        },
        {
          key: "seven_day",
          label: "Weekly",
          usedPercent: 28,
          resetsAt: "2026-08-29T07:00:00Z",
        },
        {
          key: "seven_day_fable",
          label: "Fable (weekly)",
          usedPercent: 12,
          resetsAt: "2026-08-29T07:00:00Z",
        },
        {
          key: "extra_usage",
          label: "Extra usage",
          usedPercent: 100,
          amount: { used: 600.34, total: 600, unit: "USD" },
          paid: true,
        },
      ],
    },
    {
      id: "claude-personal",
      provider: "claude",
      label: "Claude CLI · Default",
      sourceLocator: "~/.claude",
      enabled: true,
      status: "stale",
      source: "Claude subscription API (cached)",
      lastUpdatedAt: "2026-08-25T13:28:00Z",
      identity: { displayName: "me@example.com", plan: "Pro" },
      alerts: { lowQuota: false, resetSoon: false, resetHappened: false },
      autoPing: { enabled: false },
      windows: [
        {
          key: "five_hour",
          label: "Session (5h)",
          usedPercent: 18,
          resetsAt: "2026-08-25T16:00:00Z",
        },
        {
          key: "seven_day",
          label: "Weekly",
          usedPercent: 46,
          resetsAt: "2026-08-30T07:00:00Z",
        },
      ],
    },
    {
      id: "codex-default",
      provider: "codex",
      label: "Codex CLI · Default",
      sourceLocator: "~/.codex",
      enabled: true,
      status: "ready",
      source: "Codex local records",
      lastUpdatedAt: "2026-08-25T13:41:00Z",
      identity: { plan: "Plus" },
      alerts: { lowQuota: false, resetSoon: false, resetHappened: false },
      autoPing: { enabled: false },
      windows: [
        {
          key: "primary",
          label: "Session (5h)",
          usedPercent: 41,
          resetsAt: "2026-08-25T15:34:00Z",
        },
        {
          key: "secondary",
          label: "Weekly",
          usedPercent: 71,
          resetsAt: "2026-08-28T09:00:00Z",
        },
        {
          key: "credits",
          label: "Credits",
          usedPercent: 0,
          amount: { total: 12.5, unit: "USD" },
          paid: true,
        },
      ],
      resetCredits: [
        {
          id: "RateLimitResetCredit_preview-1",
          title: "Rate limit reset",
          grantedAt: "2026-08-20T09:00:00Z",
          expiresAt: "2026-09-04T14:00:00Z",
        },
      ],
    },
    {
      id: "cursor-team",
      provider: "cursor",
      label: "Cursor · work@example.com",
      sourceLocator: "oauth/cursor/user_01",
      enabled: true,
      status: "ready",
      source: "Cursor dashboard API",
      lastUpdatedAt: "2026-08-25T13:40:00Z",
      identity: { displayName: "work@example.com", plan: "Enterprise" },
      alerts: { lowQuota: false, resetSoon: false, resetHappened: false },
      autoPing: { enabled: false },
      windows: [
        {
          key: "cursor_models",
          label: "Cursor Models",
          usedPercent: 12,
          resetsAt: "2026-08-29T00:00:00Z",
        },
        {
          key: "other_models",
          label: "Other Models",
          usedPercent: 100,
          resetsAt: "2026-08-29T00:00:00Z",
        },
        {
          key: "on_demand",
          label: "On-demand",
          usedPercent: 100,
          resetsAt: "2026-08-29T00:00:00Z",
          amount: { used: 50, total: 50, unit: "USD" },
          paid: true,
        },
        {
          key: "pooled",
          label: "Team pool",
          usedPercent: 0,
          resetsAt: "2026-08-29T00:00:00Z",
          unlimited: true,
          paid: true,
        },
      ],
    },
    {
      id: "gemini-personal",
      provider: "gemini-cli",
      label: "Gemini CLI · me@example.com",
      sourceLocator: "oauth/gemini-cli/google-1",
      enabled: true,
      status: "ready",
      source: "Gemini Code Assist API",
      lastUpdatedAt: "2026-08-25T13:39:00Z",
      identity: { displayName: "me@example.com", plan: "Free" },
      alerts: { lowQuota: false, resetSoon: false, resetHappened: false },
      autoPing: { enabled: false },
      windows: [
        {
          key: "gemini-3.1-pro-preview",
          label: "Gemini 3.1 Pro Preview",
          usedPercent: 35,
          resetsAt: "2026-08-25T17:00:00Z",
        },
        {
          key: "gemini-3-flash",
          label: "Gemini 3 Flash",
          usedPercent: 12,
          resetsAt: "2026-08-25T17:00:00Z",
        },
      ],
    },
    {
      id: "copilot-mathdevie",
      provider: "copilot",
      label: "GitHub Copilot · mathdevie",
      sourceLocator: "github.com/mathdevie",
      enabled: true,
      status: "ready",
      source: "GitHub Copilot API",
      lastUpdatedAt: "2026-08-25T13:40:00Z",
      identity: { displayName: "mathdevie", plan: "Pro" },
      alerts: { lowQuota: false, resetSoon: false, resetHappened: false },
      autoPing: { enabled: false },
      windows: [
        {
          key: "premium_interactions",
          label: "AI Credits",
          usedPercent: 45,
          resetsAt: "2026-09-01T00:00:00Z",
          amount: { used: 677, total: 1500, unit: "credits", overage: 12 },
        },
        { key: "chat", label: "Chat", usedPercent: 0, unlimited: true },
        {
          key: "completions",
          label: "Completions",
          usedPercent: 0,
          unlimited: true,
        },
      ],
    },
  ],
};

/** The codex-resets.com news shown in the browser preview. */
export const previewCodexResets: CodexResetsStatus = {
  latestReset: {
    id: "observed-20260825T143200Z",
    announcedAt: "2026-08-25T14:30:00Z",
    resetType: "regular",
    text: "Reset button pressed. Enjoy!",
    sourceUrl: "https://x.com/thsottiaux/status/2092311059197808936",
  },
  activeWatch: {
    level: "strong",
    resetChancePercent: 60,
    forecastWindow: "by end of thursday",
    observedAt: "2026-08-27T06:31:31Z",
    expiresAt: "2026-08-28T07:00:00Z",
    text: "Intrigued to see if I can find the reset button tomorrow.",
    sourceUrl: "https://x.com/thsottiaux/status/2092862554632826968",
  },
  stats: {
    total: 46,
    lastResetAt: "2026-08-25T14:30:00Z",
    daysSinceLast: 1.8,
    avgIntervalDays: 7.6,
  },
  siteUrl: "https://codex-resets.com/",
  fetchedAt: "2026-08-27T09:04:36Z",
};
